kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  PortForwardWebsockets: true
nodes:
- role: control-plane
  labels:
    ingress-ready: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
- role: worker
