FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install langchain langchain-community pypdf
RUN pip3 install chromadb fastembed

COPY ./rag_chroma.py /tmp/

RUN ollama serve & sleep 1 && ollama pull gemma:2b

