FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install langchain langchain-community langchainhub pypdf
RUN pip3 install chromadb fastembed

COPY ./rag_chroma.py /home/src/
COPY ./SchoolProfile2023-2024.pdf /home/src/

RUN ollama serve & sleep 1 && ollama pull gemma:2b

