apiVersion: v2
name: llmariner
description: LLMariner transforms your GPU clusters into a powerhouse for generative AI workloads.
home: https://llmariner.ai/
icon: https://raw.githubusercontent.com/llmariner/llmariner.github.io/main/static/favicons/favicon-256.png
type: application
version: 1.1.0
appVersion: 1.1.0
dependencies:
- name: api-usage-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: cluster-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: dex-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: file-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: inference-manager-engine
  version: 1.2.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: inference-manager-server
  version: 1.2.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: job-manager-dispatcher
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: job-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: model-manager-loader
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: model-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: rbac-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: session-manager-agent
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: session-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: user-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: vector-store-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
