apiVersion: v2
name: llmariner
description: A Helm chart for LLMariner
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: api-usage-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: cluster-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: dex-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: file-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: inference-manager-engine
  version: 0.387.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: inference-manager-server
  version: 0.387.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: job-manager-dispatcher
  version: 0.222.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: job-manager-server
  version: 0.222.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: model-manager-loader
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: model-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: rbac-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: session-manager-agent
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: session-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: user-manager-server
  version: 0.98.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: vector-store-manager-server
  version: 1.0.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
