apiVersion: v2
name: llmariner
description: Scalable, extensible platform for managing generative AI workloads on Kubernetes, featuring OpenAI-compatible APIs and optimized resource management.
home: https://llmariner.ai/
icon: https://raw.githubusercontent.com/llmariner/llmariner.github.io/refs/heads/main/assets/icons/logo.svg
type: application
version: 1.5.1
appVersion: 1.5.1
sources:
  - https://github.com/llmariner/llmariner
keywords:
  - llmariner
annotations:
  "artifacthub.io/category": ai-machine-learning
  "artifacthub.io/license": Apache-2.0
dependencies:
- name: api-usage-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: cluster-manager-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: dex-server
  version: 1.3.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: file-manager-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: inference-manager-engine
  version: 1.8.1
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: inference-manager-server
  version: 1.8.1
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: job-manager-dispatcher
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: job-manager-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: model-manager-loader
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: model-manager-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: rbac-server
  version: 1.3.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: session-manager-agent
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - worker
- name: session-manager-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: user-manager-server
  version: 1.5.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
- name: vector-store-manager-server
  version: 1.1.0
  repository: "oci://public.ecr.aws/cloudnatix/llmariner-charts"
  tags:
  - control-plane
