global:
  auth:
    enable: true
    # This default value works if rbac-server runs in the same namespace.
    rbacInternalServerAddr: rbac-server-internal-grpc:8082
    # This default value works if dex-server runs in the same namespace.
    dexServerAddr: dex-server-http:5556

  # Use the default cluster registration key. This works when
  # the control plane and the worker plane are in the same cluster.
  worker:
    registrationKeySecret:
      name: default-cluster-registration-key
      key: key

  usageSender:
    # This default value works if api-usage-server runs in the same namespace.
    apiUsageInternalServerAddr: api-usage-server-internal-grpc:8082

prepare:
  database:
    # if this flag is false, llmariner uses the existing database secret.
    createSecret: false
    # secret:
    #   name: postgres
    #   password:
  objectStore:
    # if this flag is false, llmariner uses the existing aws secret.
    createSecret: false
    # secret:
    #   name: aws
    #   accessKeyId:
    #   secretAccessKey:
  workerRegistration:
    createSecret: false
    # secret:
    #   name: cluster-registration-key
    #   regKey:

tags:
  control-plane: true
  worker: true

api-usage-server:
  fullnameOverride: api-usage-server

# To avoid adding a release name prefix
cluster-manager-server:
  fullnameOverride: cluster-manager-server

dex-server:
  fullnameOverride: dex-server

file-manager-server:
  fullnameOverride: file-manager-server

inference-manager-engine:
  fullnameOverride: inference-manager-engine

inference-manager-server:
  fullnameOverride: inference-manager-server

job-manager-dispatcher:
  fullnameOverride: job-manager-dispatcher

job-manager-server:
  fullnameOverride: job-manager-server

model-manager-loader:
  fullnameOverride: model-manager-loader

model-manager-server:
  fullnameOverride: model-manager-server

rbac-server:
  fullnameOverride: rbac-server

session-manager-agent:
  fullnameOverride: session-manager-agent

session-manager-server:
  fullnameOverride: session-manager-server

user-manager-server:
  fullnameOverride: user-manager-server

vector-store-manager-server:
  fullnameOverride: vector-store-manager-server
