{{- if .Values.prepare.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prepare.database.secret.name }}
  labels:
    {{- include "llmariner.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.prepare.database.secret.password | b64enc | quote }}
{{- end }}
{{- if .Values.prepare.objectStore.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prepare.objectStore.secret.name }}
  labels:
    {{- include "llmariner.labels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.prepare.objectStore.secret.accessKeyId | b64enc | quote }}
  secretAccessKey: {{ .Values.prepare.objectStore.secret.secretAccessKey | b64enc | quote }}
{{- end }}
{{- if .Values.prepare.workerRegistration.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prepare.workerRegistration.secret.name }}
  labels:
    {{- include "llmariner.labels" . | nindent 4 }}
type: Opaque
data:
  regKey: {{ .Values.prepare.workerRegistration.secret.regKey | b64enc | quote }}
{{- end }}
