{{- if .Values.prepare.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.databaseSecret.name }}
  labels:
    {{- include "llmariner.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.global.databaseSecret.key }}: {{ .Values.prepare.database.secret.password | b64enc | quote }}
{{- end }}
{{- if .Values.prepare.objectStore.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.awsSecret.name }}
  labels:
    {{- include "llmariner.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.global.awsSecret.accessKeyIdKey }}: {{ .Values.prepare.objectStore.secret.accessKeyId | b64enc | quote }}
  {{ .Values.global.awsSecret.secretAccessKeyKey }}: {{ .Values.prepare.objectStore.secret.secretAccessKey | b64enc | quote }}
{{- end }}
{{- if .Values.prepare.workerRegistration.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.worker.registrationKeySecret.name }}
  labels:
    {{- include "llmariner.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.global.worker.registrationKeySecret.key }}: {{ .Values.prepare.workerRegistration.secret.regKey | b64enc | quote }}
{{- end }}
