name: manual-run-integration-test
on:
  workflow_dispatch:

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: install-kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        sudo install -o root -g root -m 0755 kind /usr/local/bin/kind
        rm ./kind
    - name: build-cli
      run: |
        make build
        mv ./bin/llma /usr/local/bin/llma
    - name: set-up-kind-cluster
      run: |
        ./provision/dev/create_cluster.sh single
    - name: deploy-local-helm-chart
      uses: helmfile/helmfile-action@v1.9.3
      with:
        helmfile-args: apply --skip-diff-on-install
        helmfile-workdirectory: ./provision/dev/
    - name: set-up-cli-config
      run: |
        mkdir -p ~/.config/llmariner
        cat << EOF > ~/.config/llmariner/config.yaml
        version: v1
        endpointUrl: http://localhost:8080/v1
        auth:
          clientId: llmariner
          clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
          redirectUri: http://127.0.0.1:5555/callback
          issuerUrl: http://localhost:8080/v1/dex
        context:
          organizationId:
          projectId:
        EOF
    - name: run-tests
      env:
        LLMARINER_API_KEY: default-key-secret
      run: |
        ./provision/dev/validate_deployment.sh
